### ISSUE TITLE
Erro no parse de estrutura gerada automaticamente pelo Proto

### ISSUE THREAD

**Issue by gvmonteiro** [gabstv/merger#1]
Ao utilizar a função **Merger()** para fazer o parse entre 2 estruturas diferentes, a mesma não pega os dados quando o padrão da variável é diferente, conforme o exemplo:

**Estrutura 1**

{
  CompanyID string 
}

**Estrutura 2**

{
  CompanyId string
}

**Comment by gabstv** [comment]
```go
type A struct {
CompanyID string `json:"company_id"`
}

Estrutura 2

type B struct{
CompanyId string `json:"company_id"`
}
a := &A{"company123"}
b := &B{}
merger.MergeOverwriteWithTag(b, a, "json")
```

Não funciona?

**Comment by gabstv** [comment]
Fixed on 4301712dcf8535bcb1f5bb4c1fe9e34499ee53be
